#!/bin/bash -ex
# Copyright 2026 Canonical Ltd.  All rights reserved.

bun install
bun i --global @canonical/summon @canonical/summon-component @canonical/summon-package
# cd packages/summon && bun link
# cd ../summon-component && bun link
# cd ../summon-package && bun link