#!/bin/bash -ex
# Copyright 2026 Canonical Ltd.  All rights reserved.

curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
apt-get install -y nodejs unzip
# curl -fsSL https://bun.com/install | bash
npm install -g bun@1.3.11 lerna